### ISSUE TITLE
Entity Decoding Failure

### ISSUE THREAD

**Issue by aschmitz** [ArchiveTeam/layervault-grab#2]
From IRC:

When it processes https://layervault.com/stitch-fix-deleted/blog-get-a-fix-ctas/discussions?node_path=blog-get-a-fix-ctas&sort=recent , it doesn't decode the address from &lt;meta property="og:url" content="[...]">.
 Which then leads to https://layervault.com/stitch-fix-deleted/blog-get-a-fix-ctas/discussions?node_path=blog-get-a-fix-ctas&amp;sort=recent
And then https://layervault.com/stitch-fix-deleted/blog-get-a-fix-ctas/discussions?node_path=blog-get-a-fix-ctas&amp;amp;sort=recent
And so on.

Unfortunately, I can't see where that might even be touched in the script, so I'll have to defer to someone with more pipeline experience than me.

project:3625 has that problem for me starting on request 109.

**Comment by aschmitz** [comment]
Just as a note, I've experienced this in at least two other items, although I didn't note their numbers.

**Comment by Arkiver2** [comment]
Fixed!
